services:
  - type: web
    name: applus-backend
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
